### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by isairey** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-isairey#1]
[JAVASCRIPT (2).pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-isairey/files/15204664/JAVASCRIPT.2.pdf)

**Comment by Luz1727** [comment]
bien trabajo desarrolldo con buena informacion entendible 
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
